# Generated by Django 5.1 on 2025-06-22 10:22

import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import django_tenants.postgresql_backend.base
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('role', models.CharField(choices=[('gym_owner', 'Gym Owner'), ('gym_user', 'Gym User'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('gym_trainer', 'Gym Trainer'), ('gym_staff', 'Gym Staff')], max_length=20)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('gym_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('gym_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('gym_location', models.CharField(blank=True, max_length=100, null=True)),
                ('gym_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gym_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('domain', models.SlugField(max_length=100, unique=True)),
                ('subdomain', models.CharField(blank=True, help_text="Subdomain for the tenant, e.g., 'mygym'", max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='gymowners.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GymTrainerOtherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_number', models.CharField(help_text='Emergency contact number of the trainer', max_length=15)),
                ('date_of_birth', models.DateField(help_text='Date of birth in YYYY-MM-DD format')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender of the user', max_length=10)),
                ('address', models.TextField(help_text='Address of the trainer')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood group of the trainer', max_length=3)),
                ('medical_conditions', models.TextField(blank=True, help_text='Any known medical conditions of the trainer', null=True)),
                ('past_experience', models.TextField(blank=True, help_text='Past experience of the trainer in the fitness industry', null=True)),
                ('certifications', models.TextField(blank=True, help_text='Certifications held by the trainer', null=True)),
                ('specialization', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('flexibility', 'Flexibility'), ('nutrition', 'Nutrition'), ('weightlifting', 'Weightlifting'), ('stretching', 'Stretching')], max_length=50), default=list, help_text='List of specializations of the trainer', size=None)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the trainer currently active?')),
                ('current_gym', models.ForeignKey(help_text='Current gym where the trainer is employed', on_delete=django.db.models.deletion.CASCADE, related_name='current_trainers', to='gymowners.client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GymUserOtherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('address', models.TextField(help_text='Address of the user')),
                ('batch', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('flexible', 'Flexible')], max_length=10)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood group of the user', max_length=3)),
                ('medical_conditions', models.TextField(help_text='Any known medical conditions')),
                ('fitness_goals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('fitness', 'Fitness'), ('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('competition', 'Competition')], max_length=50), default=list, help_text='List of fitness goals (e.g., weight loss, muscle gain, etc.)', size=None)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or preferences', null=True)),
                ('attachments', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, help_text='List of attachment URLs', size=None)),
                ('date_of_birth', models.DateField(help_text='Date of birth in YYYY-MM-DD format')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender of the user', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the user currently active?')),
                ('current_gym', models.ForeignKey(help_text='Current gym where the user is registered', on_delete=django.db.models.deletion.CASCADE, related_name='current_users', to='gymowners.client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerGymHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_history', to='gymowners.client')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_gym_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGymHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to='gymowners.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gym_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
