# Generated by Django 5.1 on 2025-06-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymowners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the gym location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the gym location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ratings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating of the gym out of 5', max_digits=3),
        ),
    ]
