# Generated by Django 5.1 on 2025-06-22 10:21

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(help_text='Name of the activity', max_length=100)),
                ('activity_description', models.TextField(blank=True, null=True)),
                ('repr', models.JSONField(blank=True, help_text='Representation of the activity, can be used for frontend display', null=True)),
                ('timing', models.DecimalField(decimal_places=2, help_text='Number of hours for the activity', max_digits=5)),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10), blank=True, help_text='Days of the week when the activity is available', null=True, size=None)),
                ('intensity_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='Intensity level of the activity', max_length=10)),
                ('max_participants', models.IntegerField(help_text='Maximum number of participants allowed')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or instructions for the activity', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GymActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='cardio', help_text='Name of the activity type', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('type_description', models.TextField(blank=True, help_text='Description of the activity type', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GymPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_duration', models.IntegerField(help_text='Duration in days')),
                ('package_description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(help_text='ID of the user who is logged in', verbose_name='User ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('jwt_created_at', models.DateTimeField()),
                ('jwt_expires_at', models.DateTimeField()),
                ('refresh_created_at', models.DateTimeField()),
                ('refresh_expires_at', models.DateTimeField()),
                ('jwt_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('domain_id', models.BigIntegerField(blank=True, default=None, help_text='ID of the domain where the user is logged in', null=True, verbose_name='Domain ID')),
            ],
        ),
        migrations.CreateModel(
            name='GymActivityAssignedTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.BigIntegerField(help_text='ID of the trainer assigned to the activity', verbose_name='Trainer user ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_trainers', to='accounts.gymactivity')),
            ],
        ),
        migrations.AddField(
            model_name='gymactivity',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.gymactivitytype'),
        ),
        migrations.CreateModel(
            name='GymMembersCustomActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField(help_text='ID of the user who is logged in', verbose_name='User ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.gymactivity')),
            ],
        ),
        migrations.CreateModel(
            name='GymMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(help_text='ID of the user who is a member of the gym', verbose_name='User ID')),
                ('trainer_id', models.BigIntegerField(blank=True, help_text='ID of the trainer assigned to the member', null=True, verbose_name='Trainer user ID')),
                ('membership_start_date', models.DateTimeField()),
                ('membership_end_date', models.DateTimeField(blank=True, null=True)),
                ('referred_by', models.BigIntegerField(blank=True, help_text='ID of the user who referred this member', null=True, verbose_name='Referred by user ID')),
                ('membership_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Status of the membership', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.gympackage')),
            ],
        ),
        migrations.CreateModel(
            name='GymPackageActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='accounts.gymactivity')),
                ('gym_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.gympackage')),
            ],
        ),
    ]
