# Generated by Django 5.1 on 2025-07-06 11:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymactivitytype',
            name='type_name',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.BigIntegerField(help_text='ID of the user who is attending', verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='gymactivity',
            name='activity_name',
            field=models.CharField(help_text='Name of the activity', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gympackage',
            name='package_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.BigIntegerField(help_text='ID of the user who is attending', verbose_name='User ID')),
                ('invoice', models.CharField(db_index=True, help_text='Unique invoice number for the payment', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_date', models.DateTimeField(db_index=True, help_text='Date and time of the payment')),
                ('payment_method', models.CharField(choices=[('cash', 'CASH'), ('card', 'CARD'), ('bank_transfer', 'BANK_TRANSFER'), ('upi', 'UPI'), ('other', 'OTHER')], default='cash', help_text='Method used for payment', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('paid', 'PAID'), ('failed', 'FAILED'), ('refunded', 'REFUNDED')], db_index=True, default='pending', help_text='Current status of the payment', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Additional notes about the payment', null=True)),
                ('transaction_reference_id', models.CharField(blank=True, db_index=True, help_text='Unique transaction ID from payment gateway, if applicable', max_length=100, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['payment_date', 'status'], name='accounts_pa_payment_d4c873_idx'), models.Index(fields=['user', 'payment_date'], name='accounts_pa_user_31b543_idx')],
            },
        ),
    ]
