# Generated by Django 5.1 on 2025-07-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_gymactivitytype_type_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymactivitytype',
            name='type_name',
            field=models.CharField(default='cardio', help_text='Name of the activity type', max_length=50),
        ),
    ]
