# Generated by Django 5.1 on 2025-07-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_gymactivitytype_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProvidedRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField(help_text='ID of the user who is providing the rating', verbose_name='User ID')),
                ('user_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Rating given by the user out of 5', max_digits=3)),
                ('review', models.TextField(blank=True, help_text='Review given by the user', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
