# Generated by Django 5.1 on 2025-07-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprovidedratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymmember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
