# Generated by Django 5.1 on 2025-07-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_gymmember_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymactivitytype',
            name='type_name',
            field=models.CharField(default='cardio', help_text='Name of the activity type', max_length=50, unique=True),
        ),
    ]
