# Generated by Django 5.1 on 2025-07-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_gymactivitytype_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='week_of_year',
            field=models.IntegerField(blank=True, help_text='Week of the year for the attendance record', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='year',
            field=models.IntegerField(blank=True, help_text='Year of the attendance record', null=True),
        ),
    ]
