"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config
from datetime import datetime
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOG_DIR = os.path.join(BASE_DIR, 'logs', 'django')
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, f"django_{datetime.today().date()}.log"),
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["file"],
        "level": "INFO",
    },
}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG') == 'True'

ALLOWED_HOSTS = config('ALLOWED_HOSTS').split(',')
BASE_URL = config('BASE_URL')
BASE_DOMAIN = config('BASE_DOMAIN')

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

# Application definition

TENANT_MODEL = "gymowners.Client"  # We'll create this model soon
TENANT_DOMAIN_MODEL = "gymowners.Domain"

SHARED_APPS = (
    'django_tenants',              # Always first
    'gymowners',                   # Your tenant model (e.g., Client, Domain)
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
)

TENANT_APPS = (
    'accounts',                     # Tenant-specific models like GymActivity
    # ONLY include apps with models used per tenant here.
    # DO NOT repeat shared apps like 'auth', 'rest_framework', etc.
)

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

MIDDLEWARE = [
    # 'django_tenants.middleware.TenantMainMiddleware',
    'corsheaders.middleware.CorsMiddleware',  
    # 'config.middleware.token_refresh.AutoRefreshJWTMiddleware',
    'config.middleware.schema_router.SchemaRoutingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': config('DATABASE_NAME'),
        'USER': config('DATABASE_USER'),
        'PASSWORD': config('DATABASE_PASSWORD'),
        'HOST': config('DATABASE_HOST'),
        'PORT': config('DATABASE_PORT')
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Gym Multitenant API',
    'DESCRIPTION': 'API documentation for gym owners, gym users, admins, and superadmin.',
    'VERSION': '1.0.0',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=4),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

ENVIRONMENT=config('ENVIRONMENT')

PUBLIC_SCHEMA_NAME="public"

JWT_TOKEN_EXPIRY_HOURS=4
JWT_REFRESH_TOKEN_EXPIRY_DAYS=7


AUTH_USER_MODEL = 'gymowners.CustomUser'

ROLE_GYM_OWNER = 'gym_owner'
ROLE_GYM_STAFF = 'gym_staff'
ROLE_GYM_USER = 'gym_user'
ROLE_ADMIN = 'admin'
ROLE_GYM_TRAINER = 'gym_trainer'
ROLE_SUPER_ADMIN = 'super_admin'
ROLE_CHOICES = (
    (ROLE_GYM_OWNER, 'Gym Owner'),
    (ROLE_GYM_USER, 'Gym User'),
    (ROLE_ADMIN, 'Admin'),
    (ROLE_SUPER_ADMIN, 'Super Admin'),
    (ROLE_GYM_TRAINER, 'Gym Trainer'),
    (ROLE_GYM_STAFF, 'Gym Staff'),
)
MALE = 'male'
FEMALE = 'female'
OTHER = 'other'
GENDER_CHOICES = (
    (MALE, 'Male'),
    (FEMALE, 'Female'),
    (OTHER, 'Other'),
)

BLOOD_GROUP_CHOICES  = (
    ('A+', 'A+'), 
    ('A-', 'A-'), 
    ('B+', 'B+'), 
    ('B-', 'B-'), 
    ('AB+', 'AB+'), 
    ('AB-', 'AB-'), 
    ('O+', 'O+'), 
    ('O-', 'O-'),
)

GOALS_FITNESS= "fitness"
GOALS_WEIGHT_LOSS = "weight_loss"
GOALS_MUSCLE_GAIN = "muscle_gain"
GOALS_COMPETITION = "competition"
GOAL_CHOICES = (
    (GOALS_FITNESS, 'Fitness'),
    (GOALS_WEIGHT_LOSS, 'Weight Loss'),
    (GOALS_MUSCLE_GAIN, 'Muscle Gain'),
    (GOALS_COMPETITION, 'Competition'),
)

BATCH_MORNING = 'morning'
BATCH_AFTERNOON = 'afternoon'
BATCH_EVENING = 'evening'
BATCH_NIGHT = 'night'
BATCH_FLEXIBLE = 'flexible'
BATCH_CHOICES = [
    (BATCH_MORNING, 'Morning'),
    (BATCH_AFTERNOON, 'Afternoon'),
    (BATCH_EVENING, 'Evening'),
    (BATCH_NIGHT, 'Night'),
    (BATCH_FLEXIBLE, 'Flexible'),
]


SPECIALIZATION_CARDIO = 'cardio'
SPECIALIZATION_STRENGTH = 'strength'
SPECIALIZATION_FLEXIBILITY = 'flexibility'
SPECIALIZATION_NUTRITION = 'nutrition'
SPECIALIZATION_WEIGHTLIFTING = 'weightlifting'
SPECIALIZATION_STRETCHING = 'stretching'

SPECIALIZATION_CHOICES = [
    (SPECIALIZATION_CARDIO, 'Cardio'),
    (SPECIALIZATION_STRENGTH, 'Strength'),
    (SPECIALIZATION_FLEXIBILITY, 'Flexibility'),
    (SPECIALIZATION_NUTRITION, 'Nutrition'),
    (SPECIALIZATION_WEIGHTLIFTING, 'Weightlifting'),
    (SPECIALIZATION_STRETCHING, 'Stretching'),
]


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http?://localhost(:\d+)?$",
    r"^http?://[\w\-]+\.localhost(:\d+)?$",
    r"^http?://[\d.]+\.nip\.io(:\d+)?$",  # Matches any IP with nip.io
    r"^http?://[\w\-]+\.[\d.]+\.nip\.io(:\d+)?$",  # Subdomains with IP.nip.io
    r"^http?://[\d.]+(\.\d+)*\.[\d.]+(\.\d+)*(:\d+)?$",  # Direct IP addresses
]

CSRF_TRUSTED_ORIGINS = [
    "https://*.localhost",
    "http://*.localhost",
    "https://*.nip.io", 
    "http://*.nip.io",
    "https://3.110.19.97",
    "http://3.110.19.97",
    "https://192.168.1.100",
    "http://192.168.1.100",
]


# CORS_ALLOWED_ORIGIN_REGEXES = [
#     r"^http:\/\/localhost:3000$",                                  # plain localhost
#     r"^http:\/\/[\w\-]+\.localhost:3000$",                          # subdomains like sub.localhost:3000
#     r"^http:\/\/localhost\.nip\.io:3000$",                          # localhost.nip.io
#     r"^http:\/\/[\w\-]+\.localhost\.nip\.io:3000$",                 # sub.localhost.nip.io
#     r"^http:\/\/\d{1,3}(\.\d{1,3}){3}:3000$",                        # EC2 IP like 172.31.5.10:3000
#     r"^http:\/\/[\w\-]+\.nip\.io:3000$",                            # ec2-ip.nip.io:3000
#     r"^http:\/\/[\w\-]+\.\d{1,3}(\.\d{1,3}){3}:3000$",              # subdomain.ec2-ip:3000
#     r"^http:\/\/[\w\-]+\.\d{1,3}(\.\d{1,3}){3}\.nip\.io:3000$",     # subdomain.ec2-ip.nip.io:3000
# ]

# CELERY CONFIG
CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
CELERY_TIMEZONE = 'UTC'


PUBLIC_SCHEMA_NAME = "public"

DAYS_OF_WEEKS = [
    'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=4),        # JWT expires in 4 hours
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),        # Refresh token expires in 7 days
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,                          # Your Django secret key
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

JWT_REFRESH_THRESHOLD_MINUTES = 55  # Refresh if less than 55 minutes left

ACTIVITY_INTENSITY_LEVELS = [
    ('high', 'High'),
    ('medium', 'Medium'),
    ('low', 'Low')
]
INTENSITY_HIGH = 'high'
INTENSITY_MEDIUM = 'medium'
INTENSITY_LOW = 'low'
ACTIVITY_DAYS = [
    ('monday', 'Monday'),
    ('tuesday', 'Tuesday'),
    ('wednesday', 'Wednesday'),
    ('thursday', 'Thursday'),
    ('friday', 'Friday'),
    ('saturday', 'Saturday'),
    ('sunday', 'Sunday')
]

MEMBERSHIP_STATUS_ACTIVE = 'active'
MEMBERSHIP_STATUS_INACTIVE = 'inactive'

MEMBERSHIP_STATUS_CHOICES = [
    (MEMBERSHIP_STATUS_ACTIVE, 'Active'),
    (MEMBERSHIP_STATUS_INACTIVE, 'Inactive'),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/attachments')
MEDIA_URL = '/media/attachments/'
USE_TZ = True
TIME_ZONE = 'Asia/Kolkata'